### ISSUE TITLE
Filter Not Working Properly on /editField

### ISSUE THREAD

**Issue by 0xsonu** [DSCGGV/WebD-club-project#45]
![image](https://user-images.githubusercontent.com/45717030/118426561-0c9a3500-b6e9-11eb-9bfa-da2363e3f194.png)

please correct all the field names same as in the Database.

eg:  replace electronics -> ECE as ECE available in our Database

**Comment by yuvraj-2503** [comment]
working on it.

**Comment by yuvraj-2503** [comment]
fixed the issue.
