### ISSUE TITLE
Still Showing Filter Error for this query set department=IPE

### ISSUE THREAD

**Issue by 0xsonu** [DSCGGV/WebD-club-project#46]
![image](https://user-images.githubusercontent.com/45717030/118508002-654ee980-b74c-11eb-9df4-1324e7facd94.png)

Handle all Errors using either Try-catch or conditional statement, Check whether Filtered data is not null then only show the report otherwise popup error message.

**Comment by yuvraj-2503** [comment]
Actually we are not having faculty list of IPE (6 ,8) and ECE (6,8) that is why error is showing.

**Comment by yuvraj-2503** [comment]
arrange for ECE and IPE 6th and 8th semester faculty data

**Comment by 0xsonu** [comment]
So Before showing the result, we have to filter it for null value.

**Comment by 0xsonu** [comment]
if there will no data then we have to show error popup.

**Comment by yuvraj-2503** [comment]
we can show that no data fetched alert for now and college authorities will add the data of all the semesters
